### ISSUE TITLE
Solidworks API Key Nutzung

### ISSUE THREAD

**Issue by hkauschke** [KauschkeEngineering/05001_solidworks-api#5]

**Comment by hkauschke** [comment]
Sicherstellen, dass die Nutzung des Solidworks API Key durch Dahamaa rechtlich zulässig ist.

**Comment by BigB91** [comment]
In der Mail des zugesandten Key steht folgendes dazu:
Please do not share this key with anyone outside your company or distribute it with any software you ship in plain-text format. Instead, specify the key in a compiled binary module.

Document Manager is already installed with SOLIDWORKS since SolidWorks 2004, so all you need to do is follow the example in the help file, and you should be ready to go.

Note that Document Manager changes with service packs and major releases just like SOLIDWORKS does, so be sure you are always using the correct version of the API (Installed to \Program Files\Common Files\SolidWorks Shared) and regularly get the latest help file from us as well.

Please note: Your key will allow your applications to access SOLIDWORKS files saved by any version of SOLIDWORKS, up to an including the version named above. However, you must have the named version, or a later version, of SOLIDWORKS Document Manager installed.

----


Bitte geben Sie diesen Schlüssel nicht an Personen außerhalb Ihres Unternehmens weiter und verteilen Sie ihn nicht mit Software, die Sie im Klartextformat ausliefern. Geben Sie stattdessen den Schlüssel in einem kompilierten Binärmodul an.

Document Manager wird bereits mit SOLIDWORKS seit SolidWorks 2004 installiert, so dass Sie nur noch dem Beispiel in der Hilfedatei folgen müssen, und schon sollten Sie einsatzbereit sein.

Beachten Sie, dass sich Document Manager ebenso wie SOLIDWORKS mit Service Packs und Hauptversionen ändert. Stellen Sie also sicher, dass Sie immer die richtige Version der API verwenden (installiert in \Programmdateien\Gemeinsame Dateien\SolidWorks Shared) und erhalten Sie regelmäßig die neueste Hilfedatei von uns.

Bitte beachten Sie: Mit Ihrem Schlüssel können Ihre Anwendungen auf SOLIDWORKS Dateien zugreifen, die von einer beliebigen Version von SOLIDWORKS gespeichert wurden, bis einschließlich der oben genannten Version. Sie müssen jedoch die genannte Version oder eine neuere Version von SOLIDWORKS Document Manager installiert haben.
